# 1. Import the necessary libraries
import streamlit as st 
import pandas as pd 
import numpy as np 
import plotly.graph_objects as go 
from scipy.fft import fft, fftfreq 
import os

# 2. Set up the Web Page Title
st.set_page_config(layout="wide")
st.title("🧠 3D Visualization Engine in Neurology")
st.write("**Mid-Semester Prototype:** Data Loading & Structural Rendering")

# 3. Sidebar for Navigation & Status
st.sidebar.header("Project Controls")
st.sidebar.info("Status: Dataset Integrated. \n\nNow processing real human EEG signals from the UCI database.")

# --- SECTION 1: DATASET OVERVIEW ---
st.header("1. EEG Dataset Overview")
st.write("Traditional visualization methods present EEG data as flat 2D waveforms. We are currently processing a real-world dataset to observe signal features before applying machine learning.")

# Loading the real data generated by clean_data.py
@st.cache_data
def load_eeg_data():
    csv_path = 'processed_data/clean_eeg.csv'
    if os.path.exists(csv_path):
        data = pd.read_csv(csv_path)
        # Mapping UCI channel names to the variables used in your original code
        # UCI usually names them 'FP1' and 'FP2' (uppercase)
        if 'FP1' in data.columns:
            data = data.rename(columns={'FP1': 'Fp1_Electrode', 'FP2': 'Fp2_Electrode'})
        return data, "Real Dataset (UCI)"
    else:
        # Fallback to your original simulation if CSV is missing
        time = np.linspace(0, 1, 500)
        fp1 = np.sin(20 * np.pi * time) + np.random.normal(0, 0.5, 500) 
        fp2 = np.sin(22 * np.pi * time) + np.random.normal(0, 0.5, 500)
        return pd.DataFrame({"Time (s)": time, "Fp1_Electrode": fp1, "Fp2_Electrode": fp2}), "Simulated Sample"

df, source_label = load_eeg_data()
st.sidebar.write(f"**Data Source:** {source_label}")

col1, col2 = st.columns(2)
with col1:
    st.write("Preview of Raw Data Values:")
    st.dataframe(df.head(10)) 
with col2:
    st.write("Traditional 2D Waveform View:")
    # Setting index to Time for the chart
    chart_df = df.copy()
    if 'Time (s)' in chart_df.columns:
        chart_df = chart_df.set_index("Time (s)")
    st.line_chart(chart_df[['Fp1_Electrode', 'Fp2_Electrode']]) 


# --- SECTION 2: FEATURE EXTRACTION (FFT) ---
st.header("2. Active Phase: Feature Extraction (FFT)")
st.write("Applying Fast Fourier Transform (FFT) to convert time-domain signals into frequency-domain representations.")

# Simple FFT extraction code for the Fp1 Electrode
N = len(df)
# Adjusting T to 1/256 for the real UCI dataset frequency
T = 1.0 / 256.0 
yf = fft(df['Fp1_Electrode'].values)
xf = fftfreq(N, T)[:N//2]

# Displaying the extracted features 
fig_fft = go.Figure()
fig_fft.add_trace(go.Scatter(x=xf, y=2.0/N * np.abs(yf[0:N//2]), mode='lines', name='Frequency Power', line=dict(color='orange')))
fig_fft.update_layout(title="Extracted Frequency Spectrum", xaxis_title="Frequency (Hz)", yaxis_title="Amplitude")
st.plotly_chart(fig_fft, use_container_width=True)


# --- SECTION 3: 3D ANATOMICAL STRUCTURE ---
# --- SECTION 3: 3D ANATOMICAL STRUCTURE ---
st.header("3. 3D Anatomical Structure Mapping")
st.write("The 3D engine below renders the base structure with transparent spatial axes.")

# 1. Calculate Pulse Factor from real data to maintain 'life' in the model
pulse_factor = np.std(df['Fp1_Electrode']) * 2 if 'Fp1_Electrode' in df.columns else 1.0

# 2. Generating the 3D mesh (Maintaining the dynamic radius)
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)
radius = 10 + pulse_factor

x = radius * np.outer(np.cos(u), np.sin(v))
y = radius * np.outer(np.sin(u), np.sin(v))
z = radius * np.outer(np.ones(np.size(u)), np.cos(v))

# 3. Create the figure with Transparent XYZ Axes
fig_brain = go.Figure(data=[go.Surface(
    x=x, y=y, z=z, 
    colorscale='Ice', 
    opacity=0.7,
    showscale=True 
)])

fig_brain.update_layout(
    title='Base 3D Rendering Engine Layout (Transparent Axes)',
    margin=dict(l=0, r=0, b=0, t=30),
    scene=dict(
        # Setting background to fully transparent (rgba 0,0,0,0)
        xaxis=dict(
            title='X-Axis', 
            showbackground=False, # Disables the solid color panel
            gridcolor='lightgray', # Keeps the grid lines visible
            zerolinecolor='black'
        ),
        yaxis=dict(
            title='Y-Axis', 
            showbackground=False, 
            gridcolor='lightgray',
            zerolinecolor='black'
        ),
        zaxis=dict(
            title='Z-Axis', 
            showbackground=False, 
            gridcolor='lightgray',
            zerolinecolor='black'
        ),
        aspectmode='cube'
    ),
    height=600 
)

st.plotly_chart(fig_brain, use_container_width=True)

st.success("**Next Steps for Final Evaluation:** Finalizing the dataset curation, applying K-Means clustering, loading the actual `.obj` brain model, and rendering the real-time heatmaps.")